In [ ]:
.import numpy as np

In [ ]:
np.zeros((10,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,10,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
ls = [10,20,30,40]

In [ ]:
[k+2 for k in ls]

[12, 22, 32, 42]

In [ ]:
ar = np.array(ls)

In [ ]:
ar + 2

array([12, 22, 32, 42])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.random.rand(2,4,3)

array([[[0.53991643, 0.75762228, 0.44015365],
        [0.13524872, 0.68224717, 0.32910823],
        [0.755195  , 0.72932664, 0.08479326],
        [0.18339598, 0.37419876, 0.60018364]],

       [[0.27238812, 0.75063749, 0.95451353],
        [0.84826656, 0.63652129, 0.69855215],
        [0.96998121, 0.6656336 , 0.4023096 ],
        [0.16434437, 0.07159188, 0.77849329]]])

In [ ]:
for k in range(1,10):
  np.random.rand(k)
print(k)

9


In [ ]:
np.random.randint(2,3,(6,3,9))


array([[[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2, 2, 2, 2]]])

In [ ]:
np.random.randint(11,31,(2,4,3))

array([[[29, 14, 12],
        [29, 22, 11],
        [20, 20, 19],
        [25, 21, 19]],

       [[12, 29, 29],
        [22, 25, 20],
        [18, 21, 14],
        [22, 15, 23]]])

In [ ]:
np.random.rand(11,31)

array([[0.84267729, 0.48232857, 0.96134885, 0.30690151, 0.50227058,
        0.62452424, 0.75616484, 0.07176764, 0.70312875, 0.92758525,
        0.09898921, 0.57247474, 0.76333164, 0.11038922, 0.53771207,
        0.73297031, 0.30690942, 0.76924654, 0.18836466, 0.60478418,
        0.06021819, 0.2750163 , 0.06249839, 0.02149505, 0.60656664,
        0.04663712, 0.63557297, 0.86764433, 0.67128625, 0.17398112,
        0.25884383],
       [0.43186385, 0.20302819, 0.08655321, 0.01433454, 0.53008427,
        0.93543719, 0.04272489, 0.60636515, 0.9093972 , 0.22194028,
        0.64496222, 0.28130442, 0.65819612, 0.20703615, 0.17786672,
        0.253525  , 0.69043694, 0.86912705, 0.58480873, 0.43567307,
        0.87790285, 0.86762007, 0.19656277, 0.66817539, 0.27625113,
        0.16241551, 0.49677141, 0.9582854 , 0.20721079, 0.7175875 ,
        0.40576621],
       [0.79034209, 0.27788975, 0.10875071, 0.26726424, 0.79571024,
        0.16415876, 0.86614073, 0.42271994, 0.99727776, 0.97881564,
      

In [ ]:
np.random.rand(10)

array([3.94663470e-04, 8.41894244e-01, 3.04230973e-01, 8.83506040e-01,
       2.39660172e-01, 1.29152867e-01, 5.35875583e-02, 6.93820396e-01,
       7.86889511e-01, 5.88910311e-01])

In [ ]:
np.random.choice(['cat','dog','rat'])

np.str_('cat')

In [ ]:
np.random.choice(['cat','dog','rat'],10)

array(['rat', 'dog', 'dog', 'rat', 'cat', 'rat', 'dog', 'cat', 'cat',
       'cat'], dtype='<U3')

In [ ]:
np.random.choice(['cat','dog','rat'],(10,2))

array([['cat', 'cat'],
       ['dog', 'dog'],
       ['rat', 'dog'],
       ['rat', 'dog'],
       ['cat', 'rat'],
       ['rat', 'rat'],
       ['rat', 'dog'],
       ['cat', 'cat'],
       ['cat', 'dog'],
       ['dog', 'dog']], dtype='<U3')

In [ ]:
np.random.choice(['cat','dog','rat'],100,p=[0.1,0.7,0.2])

array(['dog', 'dog', 'dog', 'dog', 'rat', 'dog', 'dog', 'dog', 'dog',
       'rat', 'dog', 'dog', 'dog', 'dog', 'dog', 'cat', 'dog', 'cat',
       'dog', 'rat', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'cat',
       'dog', 'rat', 'cat', 'dog', 'dog', 'dog', 'dog', 'rat', 'dog',
       'dog', 'dog', 'dog', 'dog', 'rat', 'dog', 'dog', 'rat', 'dog',
       'cat', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog',
       'dog', 'dog', 'dog', 'rat', 'dog', 'dog', 'cat', 'dog', 'rat',
       'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'dog', 'rat', 'dog',
       'rat', 'dog', 'cat', 'rat', 'dog', 'dog', 'rat', 'dog', 'dog',
       'dog', 'dog', 'rat', 'dog', 'rat', 'cat', 'dog', 'cat', 'dog',
       'rat', 'dog', 'dog', 'rat', 'dog', 'dog', 'dog', 'dog', 'dog',
       'dog'], dtype='<U3')

In [ ]:
np.random.randint(10,90,7)

array([55, 17, 41, 85, 82, 75, 78])

In [ ]:
np.random.seed(10)
np.random.randint(10,90,7)

array([19, 25, 74, 38, 39, 18, 83])

In [ ]:
np.random.seed(10)
np.random.randint(10,90,7)

array([19, 25, 74, 38, 39, 18, 83])

In [ ]:
arr1 = np.zeros((3,5))
arr2 = np.zeros((3,2))

In [ ]:
arr1 = np.zeros((3,5))
arr2 = np.zeros((1,5))
arr1+arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr1 = np.zeros((3,5))
arr2 = np.ones((1,5))
arr1+arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr1 = np.zeros((3,5))
arr2 = 100
arr1+arr2

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [ ]:
arr1 = np.zeros((3,5))
arr2 = 112
arr1+arr2

array([[112., 112., 112., 112., 112.],
       [112., 112., 112., 112., 112.],
       [112., 112., 112., 112., 112.]])

In [ ]:
ar1=np.random.rand(11,100,3,5)
ar2=np.random.rand(11,100,3,5)
print(ar1)
print()
print(ar2)

[[[[0.16911084 0.08833981 0.68535982 0.95339335 0.00394827]
   [0.51219226 0.81262096 0.61252607 0.72175532 0.29187607]
   [0.91777412 0.71457578 0.54254437 0.14217005 0.37334076]]

  [[0.67413362 0.44183317 0.43401399 0.61776698 0.51313824]
   [0.65039718 0.60103895 0.8052232  0.52164715 0.90864888]
   [0.31923609 0.09045935 0.30070006 0.11398436 0.82868133]]

  [[0.04689632 0.62628715 0.54758616 0.819287   0.19894754]
   [0.8568503  0.35165264 0.75464769 0.29596171 0.88393648]
   [0.32551164 0.1650159  0.39252924 0.09346037 0.82110566]]

  ...

  [[0.16563067 0.62026579 0.52421369 0.35801789 0.11278053]
   [0.66612174 0.67243338 0.77078431 0.25091438 0.87996936]
   [0.28563786 0.69738719 0.57450646 0.39046843 0.28571569]]

  [[0.19545895 0.66647755 0.82096823 0.31296957 0.28191295]
   [0.18339346 0.84657323 0.9730524  0.21092182 0.49922437]
   [0.44797555 0.6002271  0.48779845 0.30702285 0.84627405]]

  [[0.29209077 0.32263953 0.62413064 0.30148629 0.29060429]
   [0.49303752 0.645542

In [ ]:
ar1 = np.random.randint(1,10,(8,1))
ar2 = np.random.randint(1,10,(3,1))
print(ar1)
print()
print(ar2)

[[3]
 [8]
 [7]
 [9]
 [5]
 [9]
 [9]
 [3]]

[[6]
 [2]
 [5]]


In [ ]:
ar1 = np.random.randint(1,10,(3,5))
ar2 = np.random.randint(1,10,(3,2))
print(ar1)
print()
print(ar2)

[[4 4 2 6 6]
 [3 7 4 6 1]
 [3 3 7 8 2]]

[[5 9]
 [5 9]
 [4 2]]


In [ ]:
np.hstack((ar1,ar2))

array([[4, 4, 2, 6, 6, 5, 9],
       [3, 7, 4, 6, 1, 5, 9],
       [3, 3, 7, 8, 2, 4, 2]])

In [ ]:
ar1 = np.random.randint(1,10,(3,5))
ar2 = np.random.randint(1,10,(7,5))
print(ar1)
print()
print(ar2)

[[3 5 6 3 6]
 [7 3 9 6 4]
 [9 6 6 5 6]]

[[9 5 8 8 1]
 [6 3 5 1 2]
 [3 2 5 7 3]
 [4 4 1 6 4]
 [5 6 2 7 6]
 [5 5 8 4 5]
 [5 3 1 5 6]]


In [ ]:
np.vstack((ar1,ar2))

array([[3, 5, 6, 3, 6],
       [7, 3, 9, 6, 4],
       [9, 6, 6, 5, 6],
       [9, 5, 8, 8, 1],
       [6, 3, 5, 1, 2],
       [3, 2, 5, 7, 3],
       [4, 4, 1, 6, 4],
       [5, 6, 2, 7, 6],
       [5, 5, 8, 4, 5],
       [5, 3, 1, 5, 6]])

In [ ]:
rar = np.random.randint(1,9,(6,3))

In [ ]:
rar

array([[8, 6, 6],
       [7, 1, 3],
       [7, 4, 1],
       [1, 5, 1],
       [7, 3, 2],
       [5, 5, 4]])

In [ ]:
rar.reshape(1,18)

array([[8, 6, 6, 7, 1, 3, 7, 4, 1, 1, 5, 1, 7, 3, 2, 5, 5, 4]])

In [ ]:
rar.reshape(1,2,3,3)

array([[[[8, 6, 6],
         [7, 1, 3],
         [7, 4, 1]],

        [[1, 5, 1],
         [7, 3, 2],
         [5, 5, 4]]]])